# Generated by Django 4.0.7 on 2022-10-10 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('chain', models.CharField(choices=[('BINANCE', 'Binance'), ('BITCOIN', 'Bitcoin')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BitcoinTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=255)),
                ('block_hash', models.CharField(blank=True, default='_', max_length=255, null=True)),
                ('block_number', models.CharField(blank=True, default='_', max_length=255, null=True)),
                ('timestamp', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(choices=[('BINANCE', 'Binance'), ('BITCOIN', 'Bitcoin')], max_length=10)),
                ('block', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=255)),
                ('from_addr', models.CharField(blank=True, default='_', max_length=255, null=True)),
                ('to_addr', models.CharField(blank=True, default='_', max_length=255, null=True)),
                ('value', models.CharField(blank=True, default='_', max_length=255, null=True)),
                ('block_hash', models.CharField(blank=True, default='_', max_length=255, null=True)),
                ('block_number', models.CharField(blank=True, default='_', max_length=255, null=True)),
                ('timestamp', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chain', models.CharField(choices=[('BINANCE', 'Binance'), ('BITCOIN', 'Bitcoin')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('character', models.CharField(choices=[('INPUT', 'Input'), ('OUTPUT', 'Output')], max_length=10)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tx_address', to='services.bitcointransactions')),
            ],
        ),
    ]
