# Generated by Django 4.0.7 on 2022-10-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcointransactions',
            name='chain',
            field=models.CharField(choices=[('BINANCE', 'Binance'), ('BITCOIN', 'Bitcoin')], default='BITCOIN', max_length=10),
        ),
    ]
