# Generated by Django 4.0.7 on 2022-11-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_bitcointransactions_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcointransactions',
            name='status',
            field=models.CharField(choices=[('UNCONFIRMED', 'Unconfirmed'), ('CONFIRMED', 'Confirmed'), ('PARTIAL CONFIRMED', 'Partial Confirmed')], default='PARTIAL CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='bitcointransactions',
            name='chain',
            field=models.CharField(choices=[('BINANCE', 'Binance'), ('BITCOIN', 'Bitcoin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('UNCONFIRMED', 'Unconfirmed'), ('CONFIRMED', 'Confirmed'), ('PARTIAL CONFIRMED', 'Partial Confirmed')], default='PARTIAL CONFIRMED', max_length=20),
        ),
    ]
