# Generated by Django 4.0.7 on 2022-12-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_bitcointransactions_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(choices=[('BINANCE', 'Binance'), ('BITCOIN', 'Bitcoin')], max_length=10)),
                ('is_block', models.BooleanField(default=False)),
            ],
        ),
    ]
