# Generated by Django 4.0.7 on 2022-12-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_blockchainsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchainsettings',
            old_name='is_block',
            new_name='is_blocked',
        ),
    ]
