# Generated by Django 4.0.7 on 2022-12-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_is_block_blockchainsettings_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsaddress',
            name='spent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionsaddress',
            name='vout_number',
            field=models.IntegerField(default=1),
        ),
    ]
