# Generated by Django 4.0.7 on 2023-02-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_transactions_input_msg_transactions_input_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Binance transactions', 'verbose_name_plural': 'Binance transactions'},
        ),
    ]
